window.translations = {
  "tr": {
    "footer_quick": "Hızlı Bağlantılar",
    "link_about": "Hakkımızda",
    "link_contact": "İletişim",
    "nav_policies": "Politikalar",
    "policies_title": "Politikalar",
    "last_updated": "Son Güncelleme:",
    "terms_title": "Kullanım Koşulları",
    "terms_updated": "14 Ağustos 2025",
    "terms_intro": "Weltance’e hoş geldiniz. Web sitemize erişerek veya satın alma yaparak aşağıdaki koşullara bağlı olduğunuzu kabul edersiniz:",
    "terms_1": "Uygunluk – Hizmetlerimizi kullanmak için en az 18 yaşında olmalı veya ebeveyn onayına sahip olmalısınız.",
    "terms_2": "Ürünler – Tüm ürünler dijitaldir ve verilen indirme bağlantısı veya erişim yöntemiyle anında teslim edilir.",
    "terms_3": "İade Yok – Tüm satışlar kesindir. Satın almadan önce ürün açıklamalarını dikkatlice okuyunuz.",
    "terms_4": "Fikri Mülkiyet – Weltance tarafından sunulan tüm içerik, ürün ve materyaller telif hakkıyla korunur; yazılı izin olmadan kopyalanamaz, paylaşılamaz veya yeniden satılamaz.",
    "terms_5": "Sorumluluk Sınırlaması – Weltance, ürün veya hizmetlerimizi kullanmanızdan ya da kullanamamanızdan doğan zararlardan sorumlu değildir.",
    "terms_6": "Koşullardaki Değişiklikler – Bu Kullanım Koşulları’nı herhangi bir zamanda güncelleyebiliriz; hizmetlerimizi kullanmaya devam etmeniz değişiklikleri kabul ettiğiniz anlamına gelir.",
    "privacy_title": "Gizlilik Politikası",
    "privacy_updated": "14 Ağustos 2025",
    "privacy_intro": "Weltance olarak gizliliğinize saygı duyuyor ve kişisel verilerinizi korumayı taahhüt ediyoruz.",
    "privacy_1": "Topladığımız Bilgiler – Satın alma yaptığınızda adınız, e‑posta adresiniz ve ödeme bilgileri gibi verileri toplarız.",
    "privacy_2": "Bilgileri Nasıl Kullanırız – Siparişleri işlemek, ürün erişimi göndermek ve müşteri desteği sağlamak için kullanırız.",
    "privacy_3": "Veri Güvenliği – Kişisel bilgilerinizi yetkisiz erişim, ifşa veya kötüye kullanıma karşı korumak için sektör standartlarını uygularız.",
    "privacy_4": "Üçüncü Taraf Hizmetler – Güvenli üçüncü taraf ödeme sağlayıcıları kullanabiliriz. Bu hizmetlerin kendi gizlilik politikaları vardır.",
    "privacy_5": "Haklarınız – theweltance@gmail.com adresinden bize ulaşarak kişisel verilerinize erişim, düzeltme veya silme talep edebilirsiniz.",
    "privacy_6": "Politikadaki Değişiklikler – Bu Gizlilik Politikası’nı gerektiğinde güncelleyebiliriz.",
    "refund_title": "İade Politikası",
    "refund_updated": "14 Ağustos 2025",
    "refund_intro": "Weltance yalnızca dijital ürünler sunar. Dijital ürünlerin doğası gereği:",
    "refund_b1": "Tüm satışlar kesindir.",
    "refund_b2": "İade, değişim veya iptal sunmuyoruz.",
    "refund_b3": "Satın almadan önce ürün açıklamasını dikkatle inceleyiniz.",
    "refund_b4": "Ürüne erişimde teknik sorun yaşarsanız theweltance@gmail.com adresine yazın, yardımcı olacağız."
  },
  "ru": {
    "footer_quick": "Быстрые ссылки",
    "link_about": "О нас",
    "link_contact": "Контакты",
    "nav_policies": "Политики",
    "policies_title": "Политики",
    "last_updated": "Дата обновления:",
    "terms_title": "Условия использования",
    "terms_updated": "14 августа 2025 г.",
    "terms_intro": "Добро пожаловать в Weltance. Получая доступ к сайту или совершая покупку, вы соглашаетесь со следующими условиями:",
    "terms_1": "Право пользования — 18+ или согласие родителей.",
    "terms_2": "Продукты — цифровые, доступ моментально.",
    "terms_3": "Без возвратов — все продажи окончательны.",
    "terms_4": "Интеллектуальная собственность — материалы защищены авторским правом; копирование/распространение/перепродажа запрещены.",
    "terms_5": "Ограничение ответственности — Weltance не отвечает за убытки от использования или невозможности использования продуктов/сервисов.",
    "terms_6": "Изменения условий — продолжая пользоваться, принимаете обновления.",
    "privacy_title": "Политика конфиденциальности",
    "privacy_updated": "14 августа 2025 г.",
    "privacy_intro": "Мы уважаем вашу конфиденциальность и защищаем персональные данные.",
    "privacy_1": "Какие данные — имя, email, платёжные сведения.",
    "privacy_2": "Как используем — обработка заказов, доступ к продуктам, поддержка.",
    "privacy_3": "Безопасность — меры по отраслевым стандартам.",
    "privacy_4": "Сторонние сервисы — безопасные провайдеры платежей.",
    "privacy_5": "Ваши права — запросить доступ/исправление/удаление: theweltance@gmail.com.",
    "privacy_6": "Изменения политики — возможно обновление.",
    "refund_title": "Политика возврата",
    "refund_updated": "14 августа 2025 г.",
    "refund_intro": "Мы предоставляем только цифровые товары. Поэтому:",
    "refund_b1": "Все продажи окончательны.",
    "refund_b2": "Без возвратов/обменов.",
    "refund_b3": "Перед покупкой изучайте описание.",
    "refund_b4": "Проблемы с доступом? Напишите: theweltance@gmail.com."
  },
  "fr": {
    "footer_quick": "Liens utiles",
    "link_about": "À propos",
    "link_contact": "Contact",
    "nav_policies": "Politiques",
    "policies_title": "Politiques",
    "last_updated": "Dernière mise à jour :",
    "terms_title": "Conditions d’utilisation",
    "terms_updated": "14 août 2025",
    "terms_intro": "Bienvenue chez Weltance. En accédant au site ou en achetant, vous acceptez les conditions suivantes :",
    "terms_1": "Éligibilité — 18+ ou accord parental.",
    "terms_2": "Produits — 100% numériques, accès immédiat.",
    "terms_3": "Pas de remboursement — toutes les ventes sont définitives.",
    "terms_4": "Propriété intellectuelle — contenus protégés; pas de reproduction/partage/revente sans autorisation.",
    "terms_5": "Limitation de responsabilité — aucune responsabilité pour les dommages liés à l’usage.",
    "terms_6": "Modifications — l’usage continu vaut acceptation.",
    "privacy_title": "Politique de confidentialité",
    "privacy_updated": "14 août 2025",
    "privacy_intro": "Nous respectons votre vie privée et protégeons vos données personnelles.",
    "privacy_1": "Données collectées — nom, e‑mail, paiement.",
    "privacy_2": "Utilisation — traiter les commandes, donner l’accès, support.",
    "privacy_3": "Sécurité — mesures conformes aux standards.",
    "privacy_4": "Services tiers — prestataires de paiement sécurisés.",
    "privacy_5": "Vos droits — accès/rectification/suppression : theweltance@gmail.com.",
    "privacy_6": "Évolutions — la politique peut changer.",
    "refund_title": "Politique de remboursement",
    "refund_updated": "14 août 2025",
    "refund_intro": "Nous fournissons uniquement des produits numériques. En conséquence :",
    "refund_b1": "Ventes définitives.",
    "refund_b2": "Pas de remboursements/échanges.",
    "refund_b3": "Lisez la description avant achat.",
    "refund_b4": "Problème d’accès ? Écrivez à theweltance@gmail.com."
  },
  "ar": {
    "footer_quick": "روابط سريعة",
    "link_about": "من نحن",
    "link_contact": "اتصل بنا",
    "nav_policies": "السياسات",
    "policies_title": "السياسات",
    "last_updated": "تاريخ آخر تحديث:",
    "terms_title": "شروط الاستخدام",
    "terms_updated": "14 أغسطس 2025",
    "terms_intro": "باستخدام الموقع أو الشراء، فإنك توافق على الشروط التالية:",
    "terms_1": "الأهلية — 18+ أو موافقة ولي الأمر.",
    "terms_2": "المنتجات — رقمية بالكامل والوصول فوري.",
    "terms_3": "لا استرداد — جميع المبيعات نهائية.",
    "terms_4": "حقوق النشر — لا نسخ/مشاركة/إعادة بيع دون إذن.",
    "terms_5": "تحديد المسؤولية — لا تتحمل Weltance الأضرار الناتجة عن الاستخدام.",
    "terms_6": "تغييرات — قد يتم تحديث الشروط؛ الاستمرار يعني القبول.",
    "privacy_title": "سياسة الخصوصية",
    "privacy_updated": "14 أغسطس 2025",
    "privacy_intro": "نحترم خصوصيتك ونحمي بياناتك الشخصية.",
    "privacy_1": "البيانات — الاسم، البريد الإلكتروني، الدفع.",
    "privacy_2": "الاستخدام — معالجة الطلبات وتقديم الوصول والدعم.",
    "privacy_3": "الأمان — تدابير وفق المعايير.",
    "privacy_4": "خدمات طرف ثالث — مزودو دفع آمنون.",
    "privacy_5": "حقوقك — وصول/تصحيح/حذف عبر: theweltance@gmail.com.",
    "privacy_6": "تحديثات — قد تتغير السياسة.",
    "refund_title": "سياسة الاسترجاع",
    "refund_updated": "14 أغسطس 2025",
    "refund_intro": "نقدّم منتجات رقمية فقط. لذلك:",
    "refund_b1": "جميع المبيعات نهائية.",
    "refund_b2": "لا استرداد/استبدال.",
    "refund_b3": "راجع الوصف قبل الشراء.",
    "refund_b4": "مشكلة وصول؟ راسل: theweltance@gmail.com."
  },
  "de": {
    "footer_quick": "Schnellzugriff",
    "link_about": "Über uns",
    "link_contact": "Kontakt",
    "nav_policies": "Richtlinien",
    "policies_title": "Richtlinien",
    "last_updated": "Zuletzt aktualisiert:",
    "terms_title": "Nutzungsbedingungen",
    "terms_updated": "14. August 2025",
    "terms_intro": "Durch Zugriff/Kauf stimmst du Folgendem zu:",
    "terms_1": "Voraussetzungen — 18+ oder elterliche Zustimmung.",
    "terms_2": "Produkte — digital, Zugang sofort.",
    "terms_3": "Kein Widerruf — Verkäufe endgültig.",
    "terms_4": "Urheberrecht — keine Kopie/Teilung/Weiterverkauf ohne Erlaubnis.",
    "terms_5": "Haftung — keine Haftung für Schäden.",
    "terms_6": "Änderungen — weitere Nutzung gilt als Zustimmung.",
    "privacy_title": "Datenschutz",
    "privacy_updated": "14. August 2025",
    "privacy_intro": "Wir schützen deine personenbezogenen Daten.",
    "privacy_1": "Welche Daten — Name, E‑Mail, Zahlung.",
    "privacy_2": "Nutzung — Bestellungen, Zugang, Support.",
    "privacy_3": "Sicherheit — branchenübliche Maßnahmen.",
    "privacy_4": "Drittanbieter — sichere Zahlungsdienste.",
    "privacy_5": "Deine Rechte — E‑Mail: theweltance@gmail.com.",
    "privacy_6": "Updates — können erfolgen.",
    "refund_title": "Rückerstattung",
    "refund_updated": "14. August 2025",
    "refund_intro": "Nur digitale Produkte. Daher:",
    "refund_b1": "Alle Verkäufe endgültig.",
    "refund_b2": "Keine Rückerstattung/Umtausch.",
    "refund_b3": "Beschreibung vorher lesen.",
    "refund_b4": "Probleme? theweltance@gmail.com."
  },
  "en": {
    "footer_quick": "Quick Links",
    "link_about": "About",
    "link_contact": "Contact",
    "nav_policies": "Policies",
    "policies_title": "Policies",
    "last_updated": "Last Updated:",
    "terms_title": "Terms of Use",
    "terms_updated": "August 14, 2025",
    "terms_intro": "Welcome to Weltance. By accessing or purchasing from our website, you agree to be bound by the following terms:",
    "terms_1": "Eligibility – You must be at least 18 years old or have parental consent to use our services.",
    "terms_2": "Products – All products are digital and delivered instantly via the provided download link or access method.",
    "terms_3": "No Refunds – All sales are final. Please read product descriptions carefully before purchase.",
    "terms_4": "Intellectual Property – All content, products, and materials provided by Weltance are protected by copyright and may not be reproduced, shared, or resold without written permission.",
    "terms_5": "Limitation of Liability – Weltance is not liable for any damages or losses resulting from the use or inability to use our products or services.",
    "terms_6": "Changes to Terms – We may update these Terms of Use at any time, and continued use of our services means you accept the changes.",
    "privacy_title": "Privacy Policy",
    "privacy_updated": "August 14, 2025",
    "privacy_intro": "At Weltance, we respect your privacy and are committed to protecting your personal data.",
    "privacy_1": "Information We Collect – When you make a purchase, we collect information such as your name, email address, and payment details.",
    "privacy_2": "How We Use Your Information – We use your information to process orders, send product access, and provide customer support.",
    "privacy_3": "Data Security – We implement industry-standard measures to protect your personal information from unauthorized access, disclosure, or misuse.",
    "privacy_4": "Third-Party Services – We may use secure third-party payment processors. These services have their own privacy policies.",
    "privacy_5": "Your Rights – You may request access to, correction of, or deletion of your personal data by contacting us at theweltance@gmail.com.",
    "privacy_6": "Changes to Policy – We may update this Privacy Policy as needed.",
    "refund_title": "Refund Policy",
    "refund_updated": "August 14, 2025",
    "refund_intro": "Weltance provides digital products only. Due to the nature of digital goods:",
    "refund_b1": "All sales are final.",
    "refund_b2": "We do not offer refunds, returns, or exchanges.",
    "refund_b3": "Please review the product description carefully before making a purchase.",
    "refund_b4": "If you encounter technical issues accessing your product, contact us at theweltance@gmail.com, and we will assist you."
  }
};
