window.translations = {
  "en": {
    "nav_home": "Home",
    "nav_product": "Product",
    "nav_about": "About",
    "nav_contact": "Contact",
    "hero_title": "Where Ideas Thrive",
    "hero_subtitle": "Build your digital empire with clarity and confidence.",
    "chip_actionable": "Actionable",
    "chip_nofluff": "No Fluff",
    "chip_global": "Global-Ready",
    "hero_cta_primary": "Get the Pack",
    "hero_cta_secondary": "Why Weltance",
    "typed_variants": [
      "Build. Scale. Dominate.",
      "No fluff. All execution.",
      "From nobody to brand."
    ],
    "highlights_title": "Built for momentum",
    "highlight_1_t": "Start fast",
    "highlight_1_d": "Zero-to-one guidance you can apply today.",
    "highlight_2_t": "Clarity first",
    "highlight_2_d": "No noise. Only what moves the needle.",
    "highlight_3_t": "Global scale",
    "highlight_3_d": "Structure that grows with your brand.",
    "stats_creators": "Creators started",
    "stats_modules": "Modules inside",
    "stats_satisfaction": "Satisfaction (%)",
    "product_title": "Weltance Builder Pack",
    "product_desc": "From Nobody to Brand. A powerful starter kit for creators who want to build authority from zero.",
    "view_product": "View on Fourthwall",
    "testimonials_title": "What early users say",
    "features_title": "What you get",
    "feature_1_t": "Brand Playbooks",
    "feature_1_d": "Positioning, narrative, voice.",
    "feature_2_t": "Launch Engines",
    "feature_2_d": "Repeatable, compounding launches.",
    "feature_3_t": "Audience Ops",
    "feature_3_d": "Acquisition, retention, referrals.",
    "feature_4_t": "Monetization",
    "feature_4_d": "Offers, pricing, funnels.",
    "feature_5_t": "Templates",
    "feature_5_d": "Docs, scripts, checklists.",
    "feature_6_t": "Case Studies",
    "feature_6_d": "Real-world breakdowns.",
    "roadmap_title": "Roadmap",
    "roadmap_1": "Q3 • Beta cohort & feedback",
    "roadmap_2": "Q4 • Community space & weekly sprints",
    "roadmap_3": "Q1 • Advanced modules & expert sessions",
    "faq_title": "FAQ",
    "faq_1_q": "Who is this for?",
    "faq_1_a": "Creators, solopreneurs, small teams.",
    "faq_2_q": "Refunds?",
    "faq_2_a": "14-day, no-questions-asked.",
    "faq_3_q": "Updates?",
    "faq_3_a": "Continuous; pay once, get all.",
    "pricing_title": "Pricing",
    "plan_starter_t": "Starter",
    "plan_starter_d": "Core modules",
    "plan_pro_t": "Pro",
    "plan_pro_d": "All modules + updates",
    "plan_empire_t": "Empire",
    "plan_empire_d": "Pro + coaching slots",
    "price_starter": "$49",
    "price_pro": "$99",
    "price_empire": "$199",
    "choose_btn": "Choose",
    "newsletter_title": "Get one high-signal email/week",
    "subscribe_btn": "Subscribe",
    "email_placeholder": "you@brand.com",
    "blog_title": "Latest notes",
    "blog_1_t": "Zero→One Brand",
    "blog_1_d": "Positioning in 30 minutes.",
    "blog_2_t": "Launch System",
    "blog_2_d": "Repeatable, with compounding.",
    "blog_3_t": "Offer Math",
    "blog_3_d": "Build pricing power, not discounts.",
    "read_btn": "Read",
    "cta_title": "Ready to start your journey?",
    "cta_button": "Start Now",
    "mission": "Weltance — Turning raw ideas into resilient brands.",
    "why_title": "Why Weltance",
    "why_pitch": "Ship a sellable offer in 72 hours — with clarity, proof, and a repeatable system.",
    "why_b1_k": "Outcome",
    "why_b1_t": "From zero to first sale",
    "why_b1_d": "Positioning, offer math, and a simple funnel that converts.",
    "why_b2_k": "Speed",
    "why_b2_t": "Launch in days",
    "why_b2_d": "No fluff. Action checklists and templates you can ship today.",
    "why_b3_k": "Scale",
    "why_b3_t": "Built to compound",
    "why_b3_d": "Audience ops + repeatable launches = predictable growth.",
    "why_p1_v": "500+",
    "why_p1_l": "creators started",
    "why_p2_v": "10–30%",
    "why_p2_l": "typical opt-in rates",
    "why_p3_v": "72h",
    "why_p3_l": "to first offer shipped",
    "why_guarantee": "14-day, no-questions-asked refund.",
    "why_cta_primary": "Get the Builder Pack",
    "why_cta_secondary": "See pricing"
  },
  "tr": {
    "nav_home": "Ana Sayfa",
    "nav_product": "Ürün",
    "nav_about": "Hakkımızda",
    "nav_contact": "İletişim",
    "hero_title": "Fikirlerin Büyüdüğü Yer",
    "hero_subtitle": "Dijital imparatorluğunu netlik ve güvenle inşa et.",
    "chip_actionable": "Uygulanabilir",
    "chip_nofluff": "Gereksiz Yok",
    "chip_global": "Global Hazır",
    "hero_cta_primary": "Paketi Al",
    "hero_cta_secondary": "Neden Weltance",
    "typed_variants": [
      "İnşa et. Büyüt. Hakim ol.",
      "Laf değil, icraat.",
      "Hiçlikten markaya."
    ],
    "highlights_title": "Momentum için üretildi",
    "highlight_1_t": "Hızlı başla",
    "highlight_1_d": "Bugün uygulayabileceğin sıfırdan-bire rehberlik.",
    "highlight_2_t": "Önce netlik",
    "highlight_2_d": "Gürültü yok. Sadece işe yarayan adımlar.",
    "highlight_3_t": "Küresel ölçek",
    "highlight_3_d": "Markanla birlikte büyüyen yapı.",
    "stats_creators": "Başlayan üretici",
    "stats_modules": "Modül sayısı",
    "stats_satisfaction": "Memnuniyet (%)",
    "product_title": "Weltance Builder Pack",
    "product_desc": "Hiçlikten markaya. Sıfırdan otorite kurmak isteyenler için güçlü bir başlangıç paketi.",
    "view_product": "Fourthwall'da Görüntüle",
    "testimonials_title": "İlk kullanıcı yorumları",
    "features_title": "Neler var?",
    "feature_1_t": "Marka Oyun Kitapları",
    "feature_1_d": "Konumlama, anlatı, dil.",
    "feature_2_t": "Lansman Motorları",
    "feature_2_d": "Tekrarlanabilir, bileşik lansmanlar.",
    "feature_3_t": "Kitle Operasyonları",
    "feature_3_d": "Edinim, tutundurma, yönlendirme.",
    "feature_4_t": "Monetizasyon",
    "feature_4_d": "Teklifler, fiyatlama, huniler.",
    "feature_5_t": "Şablonlar",
    "feature_5_d": "Dokümanlar, scriptler, kontrol listeleri.",
    "feature_6_t": "Vaka Analizleri",
    "feature_6_d": "Gerçek dünya çözümleri.",
    "roadmap_title": "Yol Haritası",
    "roadmap_1": "Q3 • Beta grup & geribildirim",
    "roadmap_2": "Q4 • Topluluk alanı & haftalık sprintler",
    "roadmap_3": "Q1 • İleri modüller & uzman oturumları",
    "faq_title": "SSS",
    "faq_1_q": "Kimler için?",
    "faq_1_a": "Üreticiler, solo girişimciler, küçük ekipler.",
    "faq_2_q": "İade?",
    "faq_2_a": "14 gün, koşulsuz.",
    "faq_3_q": "Güncellemeler?",
    "faq_3_a": "Sürekli; bir kez öde, hepsi senin.",
    "pricing_title": "Fiyatlandırma",
    "plan_starter_t": "Başlangıç",
    "plan_starter_d": "Temel modüller",
    "plan_pro_t": "Pro",
    "plan_pro_d": "Tüm modüller + güncellemeler",
    "plan_empire_t": "İmparatorluk",
    "plan_empire_d": "Pro + koçluk saatleri",
    "price_starter": "$49",
    "price_pro": "$99",
    "price_empire": "$199",
    "choose_btn": "Seç",
    "newsletter_title": "Haftada 1 yüksek sinyalli e-posta",
    "subscribe_btn": "Abone Ol",
    "email_placeholder": "sen@marka.com",
    "blog_title": "Son notlar",
    "blog_1_t": "Sıfır→Bir Marka",
    "blog_1_d": "30 dakikada konumlama.",
    "blog_2_t": "Lansman Sistemi",
    "blog_2_d": "Tekrarlanabilir ve bileşik.",
    "blog_3_t": "Teklif Matematiği",
    "blog_3_d": "İndirim değil, değer inşa et.",
    "read_btn": "Oku",
    "cta_title": "Hazır mısın?",
    "cta_button": "Şimdi Başla",
    "mission": "Weltance — Ham fikirleri dayanıklı markalara çeviriyoruz.",
    "why_title": "Neden Weltance",
    "why_pitch": "72 saat içinde satılabilir bir teklif yayınla — netlik, kanıt ve tekrar edilebilir bir sistemle.",
    "why_b1_k": "Sonuç",
    "why_b1_t": "Sıfırdan ilk satışa",
    "why_b1_d": "Konumlama, teklif matematiği ve dönüşen basit bir huni.",
    "why_b2_k": "Hız",
    "why_b2_t": "Günler içinde lansman",
    "why_b2_d": "Gereksiz yok. Bugün uygulayacağın görev listeleri ve şablonlar.",
    "why_b3_k": "Ölçek",
    "why_b3_t": "Bileşik büyüme için",
    "why_b3_d": "Kitle operasyonları + tekrarlanabilir lansmanlar = öngörülebilir büyüme.",
    "why_p1_v": "500+",
    "why_p1_l": "başlayan üretici",
    "why_p2_v": "%10–30",
    "why_p2_l": "tipik opt-in oranı",
    "why_p3_v": "72s",
    "why_p3_l": "ilk teklife kadar süre",
    "why_guarantee": "14 gün, koşulsuz iade.",
    "why_cta_primary": "Builder Pack’i Al",
    "why_cta_secondary": "Fiyatları gör"
  },
  "ru": {
    "nav_home": "Главная",
    "nav_product": "Продукт",
    "nav_about": "О нас",
    "nav_contact": "Контакты",
    "hero_title": "Где идеи расцветают",
    "hero_subtitle": "Стройте цифровую империю ясно и уверенно.",
    "chip_actionable": "Практично",
    "chip_nofluff": "Без воды",
    "chip_global": "Готово к миру",
    "hero_cta_primary": "Получить пакет",
    "hero_cta_secondary": "Почему Weltance",
    "typed_variants": [
      "Строй. Масштабируй. Доминируй.",
      "Без воды — только дела.",
      "От никого к бренду."
    ],
    "highlights_title": "Создано для ускорения",
    "highlight_1_t": "Быстрый старт",
    "highlight_1_d": "Руководства, которые примените сегодня.",
    "highlight_2_t": "Ясность прежде всего",
    "highlight_2_d": "Без шума. Только эффект.",
    "highlight_3_t": "Мировой масштаб",
    "highlight_3_d": "Структура растёт вместе с брендом.",
    "stats_creators": "Начали создатели",
    "stats_modules": "Модулей внутри",
    "stats_satisfaction": "Удовлетворённость (%)",
    "product_title": "Weltance Builder Pack",
    "product_desc": "От никого к бренду. Сильный старт‑набор для авторитета с нуля.",
    "view_product": "Смотреть на Fourthwall",
    "testimonials_title": "Отзывы пользователей",
    "features_title": "Что вы получаете",
    "feature_1_t": "Плейбуки бренда",
    "feature_1_d": "Позиционирование, история, тон.",
    "feature_2_t": "Двигатели запусков",
    "feature_2_d": "Повторяемые, нарастающие запуски.",
    "feature_3_t": "Операции с аудиторией",
    "feature_3_d": "Привлечение, удержание, рефералы.",
    "feature_4_t": "Монетизация",
    "feature_4_d": "Офферы, цены, воронки.",
    "feature_5_t": "Шаблоны",
    "feature_5_d": "Документы, скрипты, чек‑листы.",
    "feature_6_t": "Кейсы",
    "feature_6_d": "Разборы из практики.",
    "roadmap_title": "Дорожная карта",
    "roadmap_1": "Q3 • Бета и обратная связь",
    "roadmap_2": "Q4 • Сообщество и недельные спринты",
    "roadmap_3": "Q1 • Продвинутые модули и эксперты",
    "faq_title": "Вопросы и ответы",
    "faq_1_q": "Для кого?",
    "faq_1_a": "Создатели, соло‑основатели, маленькие команды.",
    "faq_2_q": "Возвраты?",
    "faq_2_a": "14 дней, без вопросов.",
    "faq_3_q": "Обновления?",
    "faq_3_a": "Постоянно; платите один раз.",
    "pricing_title": "Цены",
    "plan_starter_t": "Старт",
    "plan_starter_d": "Базовые модули",
    "plan_pro_t": "Про",
    "plan_pro_d": "Все модули + обновления",
    "plan_empire_t": "Империя",
    "plan_empire_d": "Про + коучинг",
    "price_starter": "$49",
    "price_pro": "$99",
    "price_empire": "$199",
    "choose_btn": "Выбрать",
    "newsletter_title": "1 полезное письмо в неделю",
    "subscribe_btn": "Подписаться",
    "email_placeholder": "вы@бренд.com",
    "blog_title": "Свежие заметки",
    "blog_1_t": "Бренд Ноль→Один",
    "blog_1_d": "Позиционирование за 30 минут.",
    "blog_2_t": "Система запусков",
    "blog_2_d": "Повторяемо и с ростом.",
    "blog_3_t": "Математика оффера",
    "blog_3_d": "Создавайте ценность, не скидки.",
    "read_btn": "Читать",
    "cta_title": "Готовы начать?",
    "cta_button": "Начать",
    "mission": "Weltance — превращаем идеи в устойчивые бренды.",
    "why_title": "Почему Weltance",
    "why_pitch": "Соберите продающее предложение за 72 часа — ясно, с доказательствами и повторяемой системой.",
    "why_b1_k": "Результат",
    "why_b1_t": "От нуля к первой продаже",
    "why_b1_d": "Позиционирование, математика оффера и простая конверсионная воронка.",
    "why_b2_k": "Скорость",
    "why_b2_t": "Запуск за дни",
    "why_b2_d": "Без воды. Чек‑листы и шаблоны, которые внедрите сегодня.",
    "why_b3_k": "Масштаб",
    "why_b3_t": "Рост с накоплением",
    "why_b3_d": "Audience ops + повторные запуски = предсказуемый рост.",
    "why_p1_v": "500+",
    "why_p1_l": "создателей стартовали",
    "why_p2_v": "10–30%",
    "why_p2_l": "типовые opt‑in",
    "why_p3_v": "72ч",
    "why_p3_l": "до первого оффера",
    "why_guarantee": "14 дней — возврат без вопросов.",
    "why_cta_primary": "Получить пакет",
    "why_cta_secondary": "Смотреть цены"
  },
  "fr": {
    "nav_home": "Accueil",
    "nav_product": "Produit",
    "nav_about": "À propos",
    "nav_contact": "Contact",
    "hero_title": "Là où les idées prospèrent",
    "hero_subtitle": "Bâtissez votre empire digital avec clarté et confiance.",
    "chip_actionable": "Actionnable",
    "chip_nofluff": "Sans bla‑bla",
    "chip_global": "Prêt pour le monde",
    "hero_cta_primary": "Obtenir le pack",
    "hero_cta_secondary": "Pourquoi Weltance",
    "typed_variants": [
      "Construire. Déployer. Dominer.",
      "Sans bla‑bla, que de l’action.",
      "De personne à marque."
    ],
    "highlights_title": "Conçu pour l’élan",
    "highlight_1_t": "Démarrer vite",
    "highlight_1_d": "Conseils applicables dès aujourd’hui.",
    "highlight_2_t": "Clarté d’abord",
    "highlight_2_d": "Pas de bruit. Que l’essentiel.",
    "highlight_3_t": "Échelle mondiale",
    "highlight_3_d": "Une structure qui grandit avec votre marque.",
    "stats_creators": "Créateurs lancés",
    "stats_modules": "Modules inclus",
    "stats_satisfaction": "Satisfaction (%)",
    "product_title": "Weltance Builder Pack",
    "product_desc": "De personne à marque. Un kit puissant pour bâtir votre autorité depuis zéro.",
    "view_product": "Voir sur Fourthwall",
    "testimonials_title": "Avis d’utilisateurs",
    "features_title": "Ce que vous obtenez",
    "feature_1_t": "Playbooks de marque",
    "feature_1_d": "Positionnement, récit, ton.",
    "feature_2_t": "Moteurs de lancement",
    "feature_2_d": "Lancements répétables et cumulatifs.",
    "feature_3_t": "Ops audience",
    "feature_3_d": "Acquisition, rétention, parrainage.",
    "feature_4_t": "Monétisation",
    "feature_4_d": "Offres, prix, funnels.",
    "feature_5_t": "Modèles",
    "feature_5_d": "Docs, scripts, checklists.",
    "feature_6_t": "Études de cas",
    "feature_6_d": "Analyses concrètes.",
    "roadmap_title": "Feuille de route",
    "roadmap_1": "T3 • Cohorte bêta & retours",
    "roadmap_2": "T4 • Communauté & sprints hebdo",
    "roadmap_3": "T1 • Modules avancés & experts",
    "faq_title": "FAQ",
    "faq_1_q": "Pour qui ?",
    "faq_1_a": "Créateurs, solopreneurs, petites équipes.",
    "faq_2_q": "Remboursements ?",
    "faq_2_a": "14 jours, sans condition.",
    "faq_3_q": "Mises à jour ?",
    "faq_3_a": "Continues ; paiement unique.",
    "pricing_title": "Tarifs",
    "plan_starter_t": "Starter",
    "plan_starter_d": "Modules essentiels",
    "plan_pro_t": "Pro",
    "plan_pro_d": "Tous modules + mises à jour",
    "plan_empire_t": "Empire",
    "plan_empire_d": "Pro + coaching",
    "price_starter": "49 $",
    "price_pro": "99 $",
    "price_empire": "199 $",
    "choose_btn": "Choisir",
    "newsletter_title": "1 email à forte valeur / semaine",
    "subscribe_btn": "S’abonner",
    "email_placeholder": "vous@marque.com",
    "blog_title": "Dernières notes",
    "blog_1_t": "Marque Zéro→Un",
    "blog_1_d": "Positionnement en 30 minutes.",
    "blog_2_t": "Système de lancement",
    "blog_2_d": "Répétable et cumulatif.",
    "blog_3_t": "Maths de l’offre",
    "blog_3_d": "Créez la valeur, pas les promos.",
    "read_btn": "Lire",
    "cta_title": "Prêt à commencer ?",
    "cta_button": "Commencer",
    "mission": "Weltance — Transformer les idées brutes en marques résilientes.",
    "why_title": "Pourquoi Weltance",
    "why_pitch": "Expédiez une offre vendable en 72 h — avec clarté, preuves et un système réplicable.",
    "why_b1_k": "Résultat",
    "why_b1_t": "De zéro à la première vente",
    "why_b1_d": "Positionnement, maths de l’offre et un funnel qui convertit.",
    "why_b2_k": "Vitesse",
    "why_b2_t": "Lancement en quelques jours",
    "why_b2_d": "Sans bla‑bla. Checklists et modèles pour agir aujourd’hui.",
    "why_b3_k": "Échelle",
    "why_b3_t": "Pensé pour composer",
    "why_b3_d": "Ops audience + lancements répétables = croissance prévisible.",
    "why_p1_v": "500+",
    "why_p1_l": "créateurs lancés",
    "why_p2_v": "10–30 %",
    "why_p2_l": "taux d’inscription typiques",
    "why_p3_v": "72 h",
    "why_p3_l": "jusqu’à la première offre",
    "why_guarantee": "Remboursement sous 14 jours, sans condition.",
    "why_cta_primary": "Obtenir le pack",
    "why_cta_secondary": "Voir les tarifs"
  },
  "ar": {
    "nav_home": "الرئيسية",
    "nav_product": "المنتج",
    "nav_about": "من نحن",
    "nav_contact": "تواصل",
    "hero_title": "حيث تزدهر الأفكار",
    "hero_subtitle": "ابنِ إمبراطوريتك الرقمية بوضوح وثقة.",
    "chip_actionable": "قابل للتنفيذ",
    "chip_nofluff": "بلا حشو",
    "chip_global": "جاهز عالميًا",
    "hero_cta_primary": "احصل على الحزمة",
    "hero_cta_secondary": "لماذا وِلتانس",
    "typed_variants": [
      "ابنِ. نمِّ. سيطر.",
      "لا حشو — فعل فقط.",
      "من لا شيء إلى علامة."
    ],
    "highlights_title": "مصمم للزخم",
    "highlight_1_t": "ابدأ بسرعة",
    "highlight_1_d": "إرشادات تطبقها اليوم.",
    "highlight_2_t": "الوضوح أولاً",
    "highlight_2_d": "لا ضجيج. ما يحرّك المؤشر فقط.",
    "highlight_3_t": "قابلية التوسع عالميًا",
    "highlight_3_d": "هيكل ينمو مع علامتك.",
    "stats_creators": "مبدعون بدأوا",
    "stats_modules": "عدد الوحدات",
    "stats_satisfaction": "الرضا (%)",
    "product_title": "حزمة البناء من Weltance",
    "product_desc": "من الصفر إلى علامة. مجموعة قوية لبناء المصداقية من البداية.",
    "view_product": "اعرض على Fourthwall",
    "testimonials_title": "آراء المستخدمين الأوائل",
    "features_title": "ماذا ستحصل",
    "feature_1_t": "دلائل العلامة",
    "feature_1_d": "التموضع، السرد، النبرة.",
    "feature_2_t": "محركات الإطلاق",
    "feature_2_d": "إطلاقات قابلة للتكرار ومتراكمة.",
    "feature_3_t": "تشغيل الجمهور",
    "feature_3_d": "اكتساب، احتفاظ، إحالات.",
    "feature_4_t": "تحقيق الدخل",
    "feature_4_d": "العروض، التسعير، القُمع.",
    "feature_5_t": "قوالب",
    "feature_5_d": "مستندات، سكربتات، قوائم فحص.",
    "feature_6_t": "دراسات حالة",
    "feature_6_d": "تحليلات واقعية.",
    "roadmap_title": "خارطة الطريق",
    "roadmap_1": "الربع 3 • دفعة تجريبية وملاحظات",
    "roadmap_2": "الربع 4 • مجتمع وسبرنتات أسبوعية",
    "roadmap_3": "الربع 1 • وحدات متقدمة وجلسات خبراء",
    "faq_title": "الأسئلة الشائعة",
    "faq_1_q": "لمن؟",
    "faq_1_a": "المبدعون ورواد الأعمال والفرق الصغيرة.",
    "faq_2_q": "استرداد؟",
    "faq_2_a": "14 يومًا بلا أسئلة.",
    "faq_3_q": "تحديثات؟",
    "faq_3_a": "مستمرة؛ ادفع مرة واحدة فقط.",
    "pricing_title": "الأسعار",
    "plan_starter_t": "المبتدئ",
    "plan_starter_d": "الوحدات الأساسية",
    "plan_pro_t": "المحترف",
    "plan_pro_d": "كل الوحدات + تحديثات",
    "plan_empire_t": "الإمبراطورية",
    "plan_empire_d": "المحترف + جلسات تدريب",
    "price_starter": "$49",
    "price_pro": "$99",
    "price_empire": "$199",
    "choose_btn": "اختر",
    "newsletter_title": "رسالة أسبوعية عالية القيمة",
    "subscribe_btn": "اشترك",
    "email_placeholder": "you@brand.com",
    "blog_title": "آخر الملاحظات",
    "blog_1_t": "علامة من الصفر",
    "blog_1_d": "تموضع في 30 دقيقة.",
    "blog_2_t": "نظام الإطلاق",
    "blog_2_d": "قابل للتكرار ومتراكم.",
    "blog_3_t": "رياضيات العرض",
    "blog_3_d": "ابنِ قيمة، لا تخفيضات.",
    "read_btn": "اقرأ",
    "cta_title": "جاهز للانطلاق؟",
    "cta_button": "ابدأ الآن",
    "mission": "Weltance — نحول الأفكار الخام إلى علامات صامدة.",
    "why_title": "لماذا وِلتانس",
    "why_pitch": "أطلق عرضًا قابلاً للبيع خلال 72 ساعة — بوضوح وأدلة ونظام قابل للتكرار.",
    "why_b1_k": "النتيجة",
    "why_b1_t": "من الصفر إلى أول بيع",
    "why_b1_d": "تموضع دقيق، تسعير مدروس، وقُمع بسيط يُحوّل.",
    "why_b2_k": "السرعة",
    "why_b2_t": "إطلاق خلال أيام",
    "why_b2_d": "بلا حشو. قوائم تنفيذ وقوالب جاهزة اليوم.",
    "why_b3_k": "التوسع",
    "why_b3_t": "ينمو بتراكم",
    "why_b3_d": "تشغيل الجمهور + إطلاقات متكررة = نمو متوقع.",
    "why_p1_v": "500+",
    "why_p1_l": "مبدعين بدأوا",
    "why_p2_v": "10–30%",
    "why_p2_l": "معدلات اشتراك معتادة",
    "why_p3_v": "72س",
    "why_p3_l": "حتى أول عرض",
    "why_guarantee": "استرداد خلال 14 يومًا بلا شروط.",
    "why_cta_primary": "احصل على الحزمة",
    "why_cta_secondary": "عرض الأسعار"
  },
  "de": {
    "nav_home": "Start",
    "nav_product": "Produkt",
    "nav_about": "Über uns",
    "nav_contact": "Kontakt",
    "hero_title": "Wo Ideen gedeihen",
    "hero_subtitle": "Baue dein digitales Imperium mit Klarheit und Vertrauen.",
    "chip_actionable": "Umsetzbar",
    "chip_nofluff": "Kein Blabla",
    "chip_global": "Global bereit",
    "hero_cta_primary": "Paket holen",
    "hero_cta_secondary": "Warum Weltance",
    "typed_variants": [
      "Bauen. Skalieren. Dominieren.",
      "Kein Blabla — Taten.",
      "Von Niemand zur Marke."
    ],
    "highlights_title": "Für Momentum gebaut",
    "highlight_1_t": "Schnell starten",
    "highlight_1_d": "Anleitung, die du heute anwendest.",
    "highlight_2_t": "Klarheit zuerst",
    "highlight_2_d": "Kein Rauschen. Nur Wirkung.",
    "highlight_3_t": "Weltweite Skalierung",
    "highlight_3_d": "Struktur wächst mit deiner Marke.",
    "stats_creators": "Gestartete Creator",
    "stats_modules": "Module enthalten",
    "stats_satisfaction": "Zufriedenheit (%)",
    "product_title": "Weltance Builder Pack",
    "product_desc": "Von niemand zur Marke. Ein starkes Starter‑Kit für Autorität ab Null.",
    "view_product": "Auf Fourthwall ansehen",
    "testimonials_title": "Stimmen der Nutzer",
    "features_title": "Was du bekommst",
    "feature_1_t": "Brand‑Playbooks",
    "feature_1_d": "Positionierung, Story, Ton.",
    "feature_2_t": "Launch‑Engines",
    "feature_2_d": "Wiederholbare, kumulative Launches.",
    "feature_3_t": "Audience‑Ops",
    "feature_3_d": "Akquise, Bindung, Empfehlungen.",
    "feature_4_t": "Monetarisierung",
    "feature_4_d": "Angebote, Preise, Funnel.",
    "feature_5_t": "Vorlagen",
    "feature_5_d": "Docs, Skripte, Checklisten.",
    "feature_6_t": "Case Studies",
    "feature_6_d": "Analysen aus der Praxis.",
    "roadmap_title": "Roadmap",
    "roadmap_1": "Q3 • Beta & Feedback",
    "roadmap_2": "Q4 • Community & Wochensprints",
    "roadmap_3": "Q1 • Advanced‑Module & Experten",
    "faq_title": "FAQ",
    "faq_1_q": "Für wen?",
    "faq_1_a": "Creator, Solos, kleine Teams.",
    "faq_2_q": "Rückerstattung?",
    "faq_2_a": "14 Tage, ohne Fragen.",
    "faq_3_q": "Updates?",
    "faq_3_a": "Kontinuierlich; einmal zahlen.",
    "pricing_title": "Preise",
    "plan_starter_t": "Starter",
    "plan_starter_d": "Kernmodule",
    "plan_pro_t": "Pro",
    "plan_pro_d": "Alle Module + Updates",
    "plan_empire_t": "Empire",
    "plan_empire_d": "Pro + Coaching",
    "price_starter": "49 $",
    "price_pro": "99 $",
    "price_empire": "199 $",
    "choose_btn": "Wählen",
    "newsletter_title": "1 wertvolle Mail pro Woche",
    "subscribe_btn": "Abonnieren",
    "email_placeholder": "du@marke.com",
    "blog_title": "Neueste Notizen",
    "blog_1_t": "Marke Null→Eins",
    "blog_1_d": "Positionierung in 30 Minuten.",
    "blog_2_t": "Launch‑System",
    "blog_2_d": "Wiederholbar, mit Zinseszins.",
    "blog_3_t": "Angebots‑Mathe",
    "blog_3_d": "Wert aufbauen, keine Rabatte.",
    "read_btn": "Lesen",
    "cta_title": "Bereit zu starten?",
    "cta_button": "Jetzt starten",
    "mission": "Weltance — Rohe Ideen in belastbare Marken verwandeln.",
    "why_title": "Warum Weltance",
    "why_pitch": "In 72 Stunden ein verkaufbares Angebot — klar, belegt und wiederholbar.",
    "why_b1_k": "Ergebnis",
    "why_b1_t": "Von null zum ersten Verkauf",
    "why_b1_d": "Positionierung, Angebots‑Mathe und ein Funnel, der konvertiert.",
    "why_b2_k": "Tempo",
    "why_b2_t": "Start in Tagen",
    "why_b2_d": "Kein Blabla. Checklisten & Vorlagen für heute.",
    "why_b3_k": "Skalierung",
    "why_b3_t": "Für Zuwachs gebaut",
    "why_b3_d": "Audience‑Ops + wiederholbare Launches = planbares Wachstum.",
    "why_p1_v": "500+",
    "why_p1_l": "gestartete Creator",
    "why_p2_v": "10–30 %",
    "why_p2_l": "typische Opt‑In‑Rates",
    "why_p3_v": "72 Std",
    "why_p3_l": "bis zum ersten Angebot",
    "why_guarantee": "14‑Tage‑Rückgabe ohne Fragen.",
    "why_cta_primary": "Paket holen",
    "why_cta_secondary": "Preise ansehen"
  }
};
